#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIB3UGfAyWLdy4AgtJsDU3CQ/M1Qyfba/ts+L6cin+yn/0Pg0B/50bvI5RyRrSvHS37uA2r9sNRmnbB5Q5X0adq7S6wn1i483ggn9dZpcE11lUqUsyeqKPJCtmu5YBGk5wthLnEquZIJRBdUoolirOV3jLIbmlhOHcsYjzsZd1ofAw== rancher@blackrancher

rancher:
  console: ubuntu
  network:
    interfaces:
#RICORDARSI UTILIZZARE IL MAC ADDRESS CORRETTO DELLA SCHEDA DI RETE
#      "mac=C8:60:00:2A:40:B6":
        address: 192.168.1.46/24
        gateway: 192.168.1.254
    dns:
      nameservers:
      - 192.168.1.254
      - 8.8.8.8
      - 8.8.4.4

mounts:
#verificare che il primo parametro corrisponda alla corretta partizione "DATI" da montare
  - ["/dev/sda1", "/media/data", "ext4", ""]
