#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkWauuHubrC7nw0JV3V/XHXMNJHjwKyGJZRhca+ZEctgB76AIDD2pVmMW7UA3MMMyDK7g3/xwuyTxDKy8bi01NCofuCEyR/a+YUdDfBQj9FJE9LbLJbP2k3tk1FfnTLbExJEUNSV11HlM6CRzGxiHLwLlQXXGLluSG5DazxuMalg7RxMGTUd9/geTgsedY5Ko031NKzQALStyEmj0LUrhOFHs0MMSnGnDHRimbwPiqiQ+OKgvgtw9Nsanqbx/y6xyS6tQ4sKcVsv4KQuWQKL/xPOnpoawtVCMY3/dxyNriA1R4vGgmquw6YD10Gjcg2OO1E9Wfv0oMm+DBu0aVCllCw== plucia@linklpt-plucia

rancher:
  network:
    interfaces:
      "mac=C8:60:00:2A:40:B6":
        address: 192.168.101.200/24
        gateway: 192.168.101.1
    dns:
      nameservers:
      - 192.168.100.116
      - 192.168.100.105